---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/rockylinux/rockylinux
    pre_build_image: true
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - destroy
