---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    expected_content: "<title>Flower</title>"
  tasks:
    - name: Wait for flower to come up
      ansible.builtin.wait_for:
        timeout: 3

    - name: Debug flower status
      command: systemctl status flower.service
      register: result

    - debug: var=result
      when: result.rc != 0

    - name: Get flower logs
      command: journalctl -u flower.service
      register: logs
      when: result.rc != 0

    - debug: var=logs
      when: result.rc != 0

    - name: Get flower status
      systemd:
        name: flower.service
      register: systemd

    - name: Ensure flower is running
      assert:
        that:
          - "'active' in systemd.status.ActiveState"

    - name: Wait for webservice to be availabe
      ansible.builtin.wait_for:
        host: 0.0.0.0
        port: 5555
        delay: 1

    - name: Ensure app is Loaded
      lineinfile:
        path: /var/log/flower
        line: "     'tasks.add']"
        state: present
      check_mode: yes
      register: app
      failed_when: app is changed

    - name: Get html
      uri:
        url: http://guest:guest@localhost.localdomain:5555
        return_content: yes
      register: this
      failed_when: "expected_content not in this.content"

    - name: Ensure content type is text/html
      assert:
        that:
          - "'text/html' in this.content_type"
